[Details]
  Icon = "icons/fyne.png"
  Name = "Integrator"
  ID = "com.gcinnovate.integrator"
  Version = "1.0.0"
  Build = 12

[Development]
  HelperText = "This binary was build with debug symbol"

[Release]
  HelperText = "This binary was build without debug symbol"
